name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Install Playwright dependencies
      run: npx playwright install-deps

    - name: Install browsers
      run: npx playwright install

    - name: Test
      run: npm run test