name: Lint

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci # or yarn install
      - uses: sibiraj-s/action-eslint@v3
        with:
          extensions: 'js,jsx,ts,tsx'
          annotations: true