name: Trigger Tests for API Spec Updates

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest
    if: github.actor == 'github-actions[bot]' && startsWith(github.head_ref, 'update-weather-api-spec-')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check if PR is from weather-gov-spec workflow
        id: check-source
        run: |
          # Check if the PR branch matches our expected pattern
          if [[ "${{ github.head_ref }}" =~ ^update-weather-api-spec-[0-9]{8}-[0-9]{6}$ ]]; then
            echo "is-api-spec-pr=true" >> $GITHUB_OUTPUT
          else
            echo "is-api-spec-pr=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Trigger test workflow
        if: steps.check-source.outputs.is-api-spec-pr == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Trigger the test workflow for this PR
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test.yml',
              ref: context.payload.pull_request.head.ref
            });
            
            console.log('Test workflow triggered for PR from weather-gov-spec workflow');
            
      - name: Add comment to PR
        if: steps.check-source.outputs.is-api-spec-pr == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: '🤖 **Automated API Spec Update**\n\nThis PR contains automated updates to the weather.gov API specification. Tests have been triggered automatically.\n\n✅ Test workflow has been dispatched for this PR.'
            });