name: Publish UI

on:
  push:
      paths:
        - 'ui/**'
      branches:
        - main
        - dev

defaults:
  run:
    working-directory: ui

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: gulp build
      - uses: shallwefootball/s3-upload-action@master
        if: github.ref == 'refs/heads/dev'
        environment: 
          name: Preview
          url: https://weather-dev.parkrrr.net
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'dist'
          destination_dir: