name: Publish UI

on:
  push:
      paths:
        - 'ui/**'
      branches:
        - main
        - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    working-directory: "ui"
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: gulp build

  DeployPreview:
    name: Deploy UI (Preview)
    if: github.event_name == 'dev'
    environment: 
      name: Preview
      url: https://weather-dev.parkrrr.net
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'ui/dist'
          destination_dir:

  DeployLive:
    name: Deploy UI (Live)
    if: github.event_name == 'main'
    environment: 
      name: Live
      url: https://weather.parkrrr.net
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'ui/dist'
          destination_dir: