name: Build UI

on:
  push:
      paths:
        - 'ui/**'
      branches:
        - main
        - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm ci
        working-directory: ui
        run: npm ci
      - name: gulp build
        working-directory: ui
        run: gulp build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ui/dist
  
  DeployPreview:
    needs: Build
    name: Deploy UI (Preview)
    if: github.ref == 'refs/heads/dev'
    environment: 
      name: Preview
      url: https://weather-dev.parkrrr.net
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        name: Download artifacts
        id: download
        with:
          name: dist
      - name: Upload to S3
        with:
          args: s3 sync --delete --acl private ${{steps.download.outputs.download-path}} s3://${{secrets.AWS_BUCKET}}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"