name: Publish UI

on:
  push:
      paths:
        - 'ui/**'
      branches:
        - main
        - dev

defaults:
  run:
    working-directory: ui

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: gulp build
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: dist

  DeployPreview:
    name: Deploy UI (Preview)
    if: github.ref == 'refs/heads/dev'
    environment: 
      name: Preview
      url: https://weather-dev.parkrrr.net
    runs-on: ubuntu-latest
    steps:
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: dist
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'ui/dist'
          destination_dir:

  DeployLive:
    name: Deploy UI (Live)
    if: github.ref == 'refs/heads/main'
    environment: 
      name: Live
      url: https://weather.parkrrr.net
    runs-on: ubuntu-latest
    steps:
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: dist
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'ui/dist'
          destination_dir: